spring.application.name=omivertex

spring.datasource.url=jdbc:postgresql://localhost:5432/omivertex
spring.datasource.username=bhargavasista
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

omivertex.seed=true
