-- Résumé-extracted profile fields: contact phone + previous (external) employers.
-- Internal Softility engagement history stays allocation-derived — never merged here.
ALTER TABLE associates ADD COLUMN phone varchar(32);

CREATE TABLE employment_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    associate_id bigint NOT NULL REFERENCES associates(id) ON DELETE CASCADE,
    company varchar(120) NOT NULL,
    title varchar(120),
    start_date date,
    end_date date,
    sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX idx_employment_history_associate ON employment_history(associate_id);
