-- Flyway V1 baseline: full schema as of the initial release.
-- Generated to include all changes from V1 up to V11 consolidated.
-- Applied only under the prod profile against a fresh database.

CREATE TABLE public.clients (
    id bigint NOT NULL,
    client_id character varying(255),
    name character varying(255) NOT NULL,
    industry character varying(255),
    location character varying(255),
    status character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT clients_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);
ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.associates (
    id bigint NOT NULL,
    employee_id character varying(255),
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(32),
    company character varying(255) NOT NULL,
    location character varying(255),
    designation character varying(255),
    status character varying(255) NOT NULL,
    work_mode character varying(255) NOT NULL,
    primary_skill character varying(255),
    secondary_skill character varying(255),
    joined_date date,
    resignation_date date,
    last_working_day date,
    exit_reason character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT associates_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT associates_work_mode_check CHECK (((work_mode)::text = ANY ((ARRAY['ONSHORE'::character varying, 'OFFSHORE'::character varying])::text[]))),
    CONSTRAINT associates_exit_reason_check CHECK (exit_reason IN ('RESIGNED','TERMINATED','CONTRACT_ENDED','RETIRED','OTHER'))
);
ALTER TABLE public.associates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.associates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    associate_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT app_users_role_check CHECK (role IN ('ADMIN','VIEWER','ASSOCIATE'))
);
ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projects (
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    start_date date,
    end_date date,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ON_HOLD'::character varying, 'COMPLETED'::character varying])::text[])))
);
ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.allocations (
    id bigint NOT NULL,
    associate_id bigint NOT NULL,
    project_id bigint NOT NULL,
    allocation_percent integer NOT NULL,
    billable boolean NOT NULL,
    start_date date NOT NULL,
    end_date date,
    created_at timestamp(6) with time zone NOT NULL
);
ALTER TABLE public.allocations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allocations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.skill_categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);
ALTER TABLE public.skill_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.skills (
    id bigint NOT NULL,
    category_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);
ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.associate_skills (
    id bigint NOT NULL,
    associate_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    proficiency character varying(255) NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    CONSTRAINT associate_skills_proficiency_check CHECK (((proficiency)::text = ANY ((ARRAY['NOVICE'::character varying, 'FOUNDATIONAL'::character varying, 'INTERMEDIATE'::character varying, 'FUNCTIONAL_USER'::character varying, 'ADVANCE'::character varying, 'MASTERY'::character varying])::text[])))
);
ALTER TABLE public.associate_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.associate_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.certifications (
    id bigint NOT NULL,
    associate_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    authority character varying(255),
    credential_id character varying(255),
    issued_date date,
    expiry_date date,
    created_at timestamp(6) with time zone NOT NULL
);
ALTER TABLE public.certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.open_positions (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    allocation_percent integer NOT NULL,
    billable boolean NOT NULL,
    start_date date,
    end_date date,
    status character varying(255) NOT NULL,
    work_mode character varying(255),
    headcount integer DEFAULT 1 NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT open_positions_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'FILLED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT open_positions_work_mode_check CHECK (work_mode IN ('ONSHORE','OFFSHORE')),
    CONSTRAINT open_positions_headcount_check CHECK (headcount >= 1)
);
ALTER TABLE public.open_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.open_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.position_skills (
    id bigint NOT NULL,
    position_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    min_proficiency character varying(255),
    required boolean DEFAULT true NOT NULL,
    CONSTRAINT position_skills_min_proficiency_check CHECK (min_proficiency IN ('NOVICE','FOUNDATIONAL','INTERMEDIATE','FUNCTIONAL_USER','ADVANCE','MASTERY'))
);
ALTER TABLE public.position_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.position_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.audit_entries (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    entity_id bigint,
    entity_type character varying(255) NOT NULL,
    summary character varying(500) NOT NULL,
    "timestamp" timestamp(6) with time zone NOT NULL,
    username character varying(255) NOT NULL
);
ALTER TABLE public.audit_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resumes (
    id bigint NOT NULL,
    associate_id bigint NOT NULL,
    filename character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    byte_size bigint NOT NULL,
    content bytea NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL
);
ALTER TABLE public.resumes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.profile_change_requests (
    id bigint NOT NULL,
    associate_id bigint NOT NULL,
    type character varying(255) NOT NULL CHECK (type IN ('SKILLS','RESUME')),
    status character varying(255) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    skills_payload text,
    resume_filename character varying(255),
    resume_content_type character varying(255),
    resume_byte_size bigint,
    resume_content bytea,
    note character varying(1000),
    decided_by character varying(255),
    decided_at timestamp,
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE public.profile_change_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_change_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.employment_history (
    id bigint NOT NULL,
    associate_id bigint NOT NULL,
    company character varying(120) NOT NULL,
    title character varying(120),
    start_date date,
    end_date date,
    sort_order integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.employment_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Keys
ALTER TABLE ONLY public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.associates ADD CONSTRAINT associates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.allocations ADD CONSTRAINT allocations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_categories ADD CONSTRAINT skill_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skills ADD CONSTRAINT skills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.associate_skills ADD CONSTRAINT associate_skills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.certifications ADD CONSTRAINT certifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.open_positions ADD CONSTRAINT open_positions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.position_skills ADD CONSTRAINT position_skills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_entries ADD CONSTRAINT audit_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.resumes ADD CONSTRAINT resumes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profile_change_requests ADD CONSTRAINT profile_change_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employment_history ADD CONSTRAINT employment_history_pkey PRIMARY KEY (id);

-- Unique Constraints
ALTER TABLE ONLY public.clients ADD CONSTRAINT uk_clients_name UNIQUE (name);
ALTER TABLE ONLY public.clients ADD CONSTRAINT uk_clients_client_id UNIQUE (client_id);
ALTER TABLE ONLY public.associates ADD CONSTRAINT uk_associates_email UNIQUE (email);
ALTER TABLE ONLY public.associates ADD CONSTRAINT uk_associates_employee_id UNIQUE (employee_id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT uk_app_users_email UNIQUE (email);
ALTER TABLE ONLY public.projects ADD CONSTRAINT uk_projects_code UNIQUE (code);
ALTER TABLE ONLY public.skill_categories ADD CONSTRAINT uk_skill_categories_name UNIQUE (name);
ALTER TABLE ONLY public.skills ADD CONSTRAINT uk_skills_name_category UNIQUE (name, category_id);
ALTER TABLE ONLY public.associate_skills ADD CONSTRAINT uk_associate_skills UNIQUE (associate_id, skill_id);
ALTER TABLE ONLY public.position_skills ADD CONSTRAINT uk_position_skills UNIQUE (position_id, skill_id);
ALTER TABLE ONLY public.resumes ADD CONSTRAINT uk_resumes_associate UNIQUE (associate_id);

-- Foreign Keys
ALTER TABLE ONLY public.app_users ADD CONSTRAINT fk_app_users_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.projects ADD CONSTRAINT fk_projects_client FOREIGN KEY (client_id) REFERENCES public.clients(id);
ALTER TABLE ONLY public.allocations ADD CONSTRAINT fk_allocations_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.allocations ADD CONSTRAINT fk_allocations_project FOREIGN KEY (project_id) REFERENCES public.projects(id);
ALTER TABLE ONLY public.skills ADD CONSTRAINT fk_skills_category FOREIGN KEY (category_id) REFERENCES public.skill_categories(id);
ALTER TABLE ONLY public.associate_skills ADD CONSTRAINT fk_associate_skills_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.associate_skills ADD CONSTRAINT fk_associate_skills_skill FOREIGN KEY (skill_id) REFERENCES public.skills(id);
ALTER TABLE ONLY public.certifications ADD CONSTRAINT fk_certifications_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.open_positions ADD CONSTRAINT fk_open_positions_project FOREIGN KEY (project_id) REFERENCES public.projects(id);
ALTER TABLE ONLY public.position_skills ADD CONSTRAINT fk_position_skills_position FOREIGN KEY (position_id) REFERENCES public.open_positions(id);
ALTER TABLE ONLY public.position_skills ADD CONSTRAINT fk_position_skills_skill FOREIGN KEY (skill_id) REFERENCES public.skills(id);
ALTER TABLE ONLY public.resumes ADD CONSTRAINT fk_resumes_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.profile_change_requests ADD CONSTRAINT fk_profile_change_requests_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.employment_history ADD CONSTRAINT fk_employment_history_associate FOREIGN KEY (associate_id) REFERENCES public.associates(id) ON DELETE CASCADE;

-- Indexes
CREATE INDEX idx_employment_history_associate ON public.employment_history(associate_id);
