-- Flyway V1 baseline: full schema as of the initial production release.
-- Generated from the Hibernate-managed schema so prod 'validate' matches exactly.
-- Applied only under the prod profile against a fresh database.

CREATE TABLE public.allocations (
    id bigint NOT NULL,
    allocation_percent integer NOT NULL,
    billable boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    end_date date,
    start_date date NOT NULL,
    associate_id bigint NOT NULL,
    project_id bigint NOT NULL
);
ALTER TABLE public.allocations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.allocations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.app_users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL
);
ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.associate_skills (
    id bigint NOT NULL,
    proficiency character varying(255) NOT NULL,
    associate_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    CONSTRAINT associate_skills_proficiency_check CHECK (((proficiency)::text = ANY ((ARRAY['NOVICE'::character varying, 'FOUNDATIONAL'::character varying, 'INTERMEDIATE'::character varying, 'FUNCTIONAL_USER'::character varying, 'ADVANCE'::character varying, 'MASTERY'::character varying])::text[])))
);
ALTER TABLE public.associate_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.associate_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.associates (
    id bigint NOT NULL,
    company character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    designation character varying(255),
    email character varying(255) NOT NULL,
    location character varying(255),
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    work_mode character varying(255) NOT NULL,
    primary_skill character varying(255),
    secondary_skill character varying(255),
    CONSTRAINT associates_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT associates_work_mode_check CHECK (((work_mode)::text = ANY ((ARRAY['ONSHORE'::character varying, 'OFFSHORE'::character varying])::text[])))
);
ALTER TABLE public.associates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.associates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.audit_entries (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    entity_id bigint,
    entity_type character varying(255) NOT NULL,
    summary character varying(500) NOT NULL,
    "timestamp" timestamp(6) with time zone NOT NULL,
    username character varying(255) NOT NULL
);
ALTER TABLE public.audit_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.certifications (
    id bigint NOT NULL,
    authority character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    credential_id character varying(255),
    expiry_date date,
    issued_date date,
    name character varying(255) NOT NULL,
    associate_id bigint NOT NULL
);
ALTER TABLE public.certifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.clients (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    industry character varying(255),
    location character varying(255),
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT clients_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);
ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.open_positions (
    id bigint NOT NULL,
    allocation_percent integer NOT NULL,
    billable boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    required_skill character varying(255),
    start_date date,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    project_id bigint NOT NULL,
    min_proficiency character varying(255),
    required_skill_id bigint,
    CONSTRAINT open_positions_min_proficiency_check CHECK (((min_proficiency)::text = ANY ((ARRAY['NOVICE'::character varying, 'FOUNDATIONAL'::character varying, 'INTERMEDIATE'::character varying, 'FUNCTIONAL_USER'::character varying, 'ADVANCE'::character varying, 'MASTERY'::character varying])::text[]))),
    CONSTRAINT open_positions_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'FILLED'::character varying, 'CANCELLED'::character varying])::text[])))
);
ALTER TABLE public.open_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.open_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.projects (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    end_date date,
    name character varying(255) NOT NULL,
    start_date date,
    status character varying(255) NOT NULL,
    client_id bigint NOT NULL,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ON_HOLD'::character varying, 'COMPLETED'::character varying])::text[])))
);
ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.skill_categories (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL
);
ALTER TABLE public.skill_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.skills (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    category_id bigint NOT NULL
);
ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.allocations
    ADD CONSTRAINT allocations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.associate_skills
    ADD CONSTRAINT associate_skills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.associates
    ADD CONSTRAINT associates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_entries
    ADD CONSTRAINT audit_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.certifications
    ADD CONSTRAINT certifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.open_positions
    ADD CONSTRAINT open_positions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_categories
    ADD CONSTRAINT skill_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.skill_categories
    ADD CONSTRAINT uk27adsrrs9xq470bq9eui9x03c UNIQUE (name);
ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);
ALTER TABLE ONLY public.skills
    ADD CONSTRAINT uk6xwpqyc9atwrwby4q5cgx61pj UNIQUE (name, category_id);
ALTER TABLE ONLY public.projects
    ADD CONSTRAINT ukclujw4wu21d33ssgde022aymk UNIQUE (code);
ALTER TABLE ONLY public.associate_skills
    ADD CONSTRAINT ukiwye2ot5fdjao8ofaq9b82x8l UNIQUE (associate_id, skill_id);
ALTER TABLE ONLY public.clients
    ADD CONSTRAINT ukk49t374y88hquc0xxwg5iudfv UNIQUE (name);
ALTER TABLE ONLY public.associates
    ADD CONSTRAINT ukp125q7el6tqc9qc8hqu7r466v UNIQUE (email);
ALTER TABLE ONLY public.associate_skills
    ADD CONSTRAINT fk7jqisohkvohhsd2wmcx6re4r4 FOREIGN KEY (skill_id) REFERENCES public.skills(id);
ALTER TABLE ONLY public.allocations
    ADD CONSTRAINT fk8sfy65ewwbf7n9ll1qpxg9vay FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.associate_skills
    ADD CONSTRAINT fke75t4sdon2q19o5r8ixxe6c2f FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.open_positions
    ADD CONSTRAINT fkf2ktwrm0s5r0wwnedb471080q FOREIGN KEY (required_skill_id) REFERENCES public.skills(id);
ALTER TABLE ONLY public.certifications
    ADD CONSTRAINT fkjtqhqfh8hrd4wm34kcr0whvrc FOREIGN KEY (associate_id) REFERENCES public.associates(id);
ALTER TABLE ONLY public.projects
    ADD CONSTRAINT fkksdiyuily2f4ca2y53k07pmq FOREIGN KEY (client_id) REFERENCES public.clients(id);
ALTER TABLE ONLY public.skills
    ADD CONSTRAINT fkl16l87m9kquuuuecnq1fx5hem FOREIGN KEY (category_id) REFERENCES public.skill_categories(id);
ALTER TABLE ONLY public.allocations
    ADD CONSTRAINT fklgyvi1ifhphug0govaqwnsqyf FOREIGN KEY (project_id) REFERENCES public.projects(id);
ALTER TABLE ONLY public.open_positions
    ADD CONSTRAINT fksf6dorymflnpxm1df1j9h4t7b FOREIGN KEY (project_id) REFERENCES public.projects(id);
