-- A position now demands a LIST of skills (must-have / nice-to-have with a minimum
-- proficiency) plus an optional work-mode constraint. The old single structured
-- skill columns migrate into the new table as one must-have row.
CREATE TABLE position_skills (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id bigint NOT NULL REFERENCES open_positions(id),
    skill_id bigint NOT NULL REFERENCES skills(id),
    min_proficiency varchar(255),
    required boolean NOT NULL DEFAULT true,
    CONSTRAINT position_skills_unique UNIQUE (position_id, skill_id),
    CONSTRAINT position_skills_min_proficiency_check CHECK (min_proficiency IN
        ('NOVICE','FOUNDATIONAL','INTERMEDIATE','FUNCTIONAL_USER','ADVANCE','MASTERY'))
);

INSERT INTO position_skills (position_id, skill_id, min_proficiency, required)
SELECT id, required_skill_id, min_proficiency, true
FROM open_positions WHERE required_skill_id IS NOT NULL;

ALTER TABLE open_positions DROP COLUMN required_skill_id;
ALTER TABLE open_positions DROP COLUMN min_proficiency;
ALTER TABLE open_positions ADD COLUMN work_mode varchar(255);
ALTER TABLE open_positions ADD CONSTRAINT open_positions_work_mode_check
    CHECK (work_mode IN ('ONSHORE','OFFSHORE'));
