-- Self-service: an ASSOCIATE-role login is linked to their roster record.
ALTER TABLE app_users ADD COLUMN associate_id bigint REFERENCES associates(id);
ALTER TABLE app_users DROP CONSTRAINT IF EXISTS app_users_role_check;
ALTER TABLE app_users ADD CONSTRAINT app_users_role_check
    CHECK (role IN ('ADMIN','VIEWER','ASSOCIATE'));

-- An associate's proposed profile edit; live data changes only on admin approval.
CREATE TABLE profile_change_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    associate_id bigint NOT NULL REFERENCES associates(id),
    type varchar(255) NOT NULL CHECK (type IN ('SKILLS','RESUME')),
    status varchar(255) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    skills_payload text,
    resume_filename varchar(255),
    resume_content_type varchar(255),
    resume_byte_size bigint,
    resume_content bytea,
    note varchar(1000),
    decided_by varchar(255),
    decided_at timestamp,
    created_at timestamp NOT NULL DEFAULT now()
);
